/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoDS;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	App meuApp = new App();
        System.out.println(meuApp.getGreeting());
    }
}
